/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#004e5c",
        "tertiary-fixed": "#acedff",
        "outline-variant": "#bcc9c6",
        "on-secondary": "#ffffff",
        "inverse-surface": "#213145",
        "tertiary-fixed-dim": "#4cd7f6",
        "on-primary-fixed-variant": "#005049",
        "secondary-fixed-dim": "#bec6e0",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#3d4947",
        "on-primary-fixed": "#00201d",
        "tertiary-container": "#008096",
        "on-secondary-container": "#5c647a",
        "on-tertiary-fixed": "#001f26",
        "inverse-on-surface": "#eaf1ff",
        "outline": "#6d7a77",
        "secondary": "#565e74",
        "on-primary": "#ffffff",
        "surface-container-low": "#eff4ff",
        "secondary-fixed": "#dae2fd",
        "primary-container": "#008378",
        "surface-dim": "#cbdbf5",
        "surface-container-high": "#dce9ff",
        "on-secondary-fixed-variant": "#3f465c",
        "surface-container-highest": "#d3e4fe",
        "surface-tint": "#006a61",
        "on-background": "#0b1c30",
        "on-surface": "#0b1c30",
        "background": "#f8f9ff",
        "surface-container": "#e5eeff",
        "surface": "#f8f9ff",
        "inverse-primary": "#6bd8cb",
        "on-primary-container": "#f4fffc",
        "primary-fixed": "#89f5e7",
        "on-secondary-fixed": "#131b2e",
        "error-container": "#ffdad6",
        "tertiary": "#006577",
        "on-tertiary-container": "#f9fdff",
        "surface-variant": "#d3e4fe",
        "secondary-container": "#dae2fd",
        "primary-fixed-dim": "#6bd8cb",
        "error": "#ba1a1a",
        "primary": "#00685f",
        "on-error-container": "#93000a",
        "surface-bright": "#f8f9ff",
        "on-error": "#ffffff"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {
        gutter: "1.5rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        "margin-mobile": "1rem",
        "space-md": "1rem",
        "gutter-mobile": "0.75rem",
        margin: "2rem",
        "space-sm": "0.5rem",
        "space-xs": "0.25rem"
      },
      fontFamily: {
        heading: ['"Plus Jakarta Sans"', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        "body-lg": ["Inter", "sans-serif"],
        "headline-sm": ['"Plus Jakarta Sans"', "sans-serif"],
        "headline-md": ['"Plus Jakarta Sans"', "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "display-hero-mobile": ['"Plus Jakarta Sans"', "sans-serif"],
        "display-hero": ['"Plus Jakarta Sans"', "sans-serif"],
        "metric-display": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ['"Plus Jakarta Sans"', "sans-serif"],
        "headline-lg-mobile": ['"Plus Jakarta Sans"', "sans-serif"],
        "code-telemetry": ["Inter", "sans-serif"],
        "metric-label": ["Inter", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "headline-sm": ["18px", { lineHeight: "26px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "18px", letterSpacing: "0.005em", fontWeight: "400" }],
        "label-sm": ["11px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "600" }],
        "label-md": ["13px", { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "500" }],
        "display-hero-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-hero": ["48px", { lineHeight: "56px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "metric-display": ["32px", { lineHeight: "36px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.025em", fontWeight: "600" }],
        "headline-lg-mobile": ["26px", { lineHeight: "34px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "code-telemetry": ["11px", { lineHeight: "14px", letterSpacing: "0.02em", fontWeight: "500" }],
        "metric-label": ["11px", { lineHeight: "14px", letterSpacing: "0.06em", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}

